notifications:
  email: false

git:
  depth: 1

matrix:
  include:
    - os: linux
      go:
        - 1.x
      cache:
        directories:
          - $HOME/.cache/go-build
          - $HOME/gopath/pkg/mod

    - os: osx
      go:
        - 1.x
      cache:
        directories:
          - $HOME/Library/Caches/go-build
          - $HOME/gopath/pkg/mod
