apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: khanzo-jubei
  namespace: blackrock
spec:
  serviceName: "khanzo-jubei"
  replicas: 3
  selector:
    matchLabels:
      app: khanzo-jubei
  template:
    metadata:
      labels:
        app: khanzo-jubei
    spec:
      containers:
      - name: jubei
        image: "jackdoe/blackrock:0.6"
        env:
        - name: TOPIC
          value: "blackrock-data"
        - name: TOPIC_CTX
          value: "blackrock-context"
        - name: BROKERS
          value: "localhost:9092"
        - name: BROKERS
          value: "localhost:9092"
        volumeMounts:
        - name: data
          mountPath: /blackrock
        command: ["/bin/jubei"]
        args: ["-topic-data","$(TOPIC)","-topic-context","$(TOPIC_CTX)", "-kafka","$(BROKERS)","-verbose"]
      - name: khanzo
        image: "jackdoe/blackrock:0.6"
        env:
        - name: BIND
          value: ":7001"
        - name: TOPIC
          value: "blackrock-data"
        volumeMounts:
        - name: data
          mountPath: /blackrock
        livenessProbe:
          httpGet:
            path: /health
            port: 7001
          initialDelaySeconds: 1
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 7001
          initialDelaySeconds: 1
          periodSeconds: 3
        command: ["/bin/khanzo"]
        args: ["-root","/blackrock/$(TOPIC)","-bind","$(BIND)","-verbose"]
        ports:
        - containerPort: 7001
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

