---
apiVersion: v1
kind: Service
metadata:
  namespace: blackrock
  labels:
    name: orgrim-np
  name: orgrim-np
spec:
  type: NodePort
  ports:
  - port: 7000
    targetPort: 7000
    protocol: TCP
  selector:
    app: orgrim
