---
apiVersion: v1
kind: Service
metadata:
  namespace: blackrock
  labels:
    name: blackhand-np
  name: blackhand-np
spec:
  type: NodePort
  ports:
  - port: 7002
    targetPort: 7002
    protocol: TCP
  selector:
    app: blackhand
