---
apiVersion: v1
kind: Service
metadata:
  namespace: blackrock
  labels:
    name: khanzo-np
  name: khanzo-np
spec:
  type: NodePort
  ports:
  - port: 7001
    targetPort: 7001
    protocol: TCP
  selector:
    app: khanzo-jubei
